### ISSUE TITLE
Using off the shelf NFC reader for final solution 3

### ISSUE THREAD

**Issue by gregid** [gdarchen/webusb-arduino-nfc#92]
What is the reason one cannot use off the shelf USB NFC reader for the client solution. Is there anything that will make it not working without custom arduino hardware?

I couldn't find any explanation for this.

**Comment by gdarchen-kannelle** [comment]
> What is the reason one cannot use off the shelf USB NFC reader for the client solution. Is there anything that will make it not working without custom arduino hardware?
> 
> 
> 
> I couldn't find any explanation for this.

Hi @gregid,

The shelf USB NFC reader acts like a keyboard. When some tag is scanned onto the shelf, the scanned text will be written in the focused file/form field. You can't get its output to use it directly in your JavaScript code. I hope it's clearer now 😊

**Comment by gdarchen** [comment]
Hi @gregid ,

The shelf USB NFC reader acts like a keyboard. 
When some tag is scanned onto the shelf, the scanned text will be written in the focused file/form field. 
You can't get its output to use it directly in your JavaScript code. 

I hope it's clearer now 😊
